// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userProto.proto

package project.grpc.pd.protos;

public interface UsuarioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usuarioProto.Usuario)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string nome = 2;</code>
   */
  java.lang.String getNome();
  /**
   * <code>string nome = 2;</code>
   */
  com.google.protobuf.ByteString
      getNomeBytes();
}
